query ReviewRuleList {
  rules {    
    ...ReviewRuleListItem
  }
}


fragment ReviewRuleListItem on ReviewRule {
  id
  trigger {
    triggerName
  }
  condition {
    property
    value
  }
  effect {
    name
  }
}