# Generated by Django 4.1.2 on 2022-10-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(choices=[('is_nth_review', 'Is Nth Review'), ('decision_is', 'Decision Is'), ('all_decisions_match', 'All Decisions Match')], max_length=100)),
                ('value', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('close_job', 'Close'), ('delete_and_close', 'Delete And Close'), ('nothing', 'Nothing')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_name', models.CharField(max_length=200, unique=True)),
                ('sender', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(choices=[('published', 'Published'), ('deleted', 'Deleted')], default='published', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postreviewjob',
            name='status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='unreviewed', max_length=50),
            preserve_default=False,
        ),
    ]
