# Generated by Django 4.1.2 on 2022-10-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviewrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='trigger_name',
            field=models.CharField(choices=[('on_review_create', 'On Review Create')], max_length=200),
        ),
    ]
