# Generated by Django 4.1.2 on 2022-10-30 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_trigger_trigger_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreview',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.postreviewjob'),
        ),
        migrations.AlterField(
            model_name='postreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.reviewer'),
        ),
    ]
