# Generated by Django 4.1.2 on 2022-11-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_postreview_job_alter_postreview_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrule',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewrule',
            name='success_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
